<?php
/*
 * Модуль dfunc_map
 */

// машинное имя типа материала, который должен отображаться на карте
define('DM_OBJECT_NODE_TYPE_NAME', 'service_center');
// машинное имя вьюса, который должен содержать карту
define('DM_MAP_VIEW_NAME', 'map');
// машинное имя дисплея вьюса, который должен содержать карту
define('DM_MAP_DISPLAY_NAME', 'page_1');

define('DM_CITIES_VIEW_DISPLAY_NAME', 'block_1');

define('DM_BASE_URL', '/servisnie-centri');

function dfunc_map_views_post_render(&$views) {
 // dsm($views); 
}
function dfunc_map_views_pre_render(&$view) {
  switch ($view->name) {
    case DM_MAP_VIEW_NAME:
      switch ($view->current_display) {
        case DM_MAP_DISPLAY_NAME:
          dm_add_js_vars_about_objects($view);
          dm_add_js_vars_about_cities();
          dm_add_scripts();
          break;
      }
      break;
  }
}


/**
 * Создает в js объекты, содержащие данные о найденных объектах,
 * которые надо отобразить на карте
 */
function dm_add_js_vars_about_objects($view) {
  $objects = array();

  $results = $view->result;
  if (!empty($results)) {
    foreach ($results as $i => $row) {
      $object = array(
        'title' => $row->node_title,
        'address' => $row->node_data_field_lon_field_address_value,
        'nid' => $row->nid,
        'lat' => $row->node_data_field_lon_field_lat_value,
        'lon' => $row->node_data_field_lon_field_lon_value,
      );
      $objects[] = $object;
    }
  }

  // выводим в js все найденные объекты
  drupal_add_js(array(
    'dfunc_map' => array(
      'map_objects' => $objects,
    ),
  ), 'setting');
}

function dm_add_scripts() {
  $external_js = 'http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU';
  drupal_add_js('document.write(unescape("%3Cscript src=\''. $external_js . '\' type=\'text/javascript\'%3E%3C/script%3E"));', 'inline');

  $module_path = drupal_get_path('module', 'dfunc_map');
  drupal_add_js($module_path . '/js/dm_map.js');
  drupal_add_js($module_path . '/js/dm_city_filter.js');

  drupal_add_css($module_path . '/css/dm_map.css');
}

/**
 * Implements hook_theme().
 */
function dfunc_map_theme() {
  $module_path = drupal_get_path('module', 'dfunc_map');
  $tpl_path = $module_path . '/tpl';
  return array(
    'views_view_unformatted__map__page_1' => array(
      'arguments' => array(
        'view'    => NULL, 
        'title'   => NULL, 
        'rows'    => NULL, 
        'classes' => NULL
      ),
      'template' => 'views-view-unformatted--map--page-1',
      'original hook' => 'views_view_unformatted',
      'path' => $tpl_path,
      'theme path' => $tpl_path,
      'theme paths' => array($tpl_path),
    ),

    'dm_cities_links' => array(
      'arguments' => array(
        'links'   => NULL, 
      ),
      'template' => 'cities_links',
      // 'original hook' => 'block',
      'path' => $tpl_path,
      'theme path' => $tpl_path,
      'theme paths' => array($tpl_path),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dfunc_map_form_alter(&$form, &$form_state, $form_id) {
  $exposed_map_form_id = sprintf('views_exposed_form_%s_%s', DM_MAP_VIEW_NAME, DM_MAP_DISPLAY_NAME);
  $exposed_map_form_id = str_replace('-', '_', $exposed_map_form_id);
  $form_inner_id       = str_replace('-', '_', $form['#id']);

  if ('views_exposed_form' == $form_id && $exposed_map_form_id == $form_inner_id) {
    $form['#after_build'][] = 'exposed_city_autocomplete_after_build';
  }
}

function exposed_city_autocomplete_after_build($form, &$form_state) {
  $form['city']['#autocomplete_path'] = 'dm/city-autocomplete';
  $form['city']['#value'] = 'Введите название города ...';
  $form['city']['#attributes'] = array('class' => 'NormalTextBox txtSearch',
                                                              'onfocus' => "if (this.value == 'Введите название города ...') {this.value = '';}",
                                                              'onblur' => "if (this.value == '') {this.value = 'Введите название города ...';}");
  return $form;
}

function dfunc_map_menu() {
    $items['dm/city-autocomplete'] = array(
        'page callback' => 'dm_city_autocomplete',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
    );
    return $items;
}

function dm_city_autocomplete($string) {
  if (empty($string)) {
    exit();
  }

  $field_city_col = 'field_city_value';
  $tbl = "content_field_city";
  $content_type = DM_OBJECT_NODE_TYPE_NAME;

  $query = "select $field_city_col from {$tbl}  inner join node on node.nid=$tbl.nid where node.type='$content_type' and $field_city_col like '%$string%'";

  $result = db_query($query, $field_city_col, $tbl, $field_city_col, '%'.$string.'%');

  $matches = array();
  while ($row = db_fetch_array($result)) {
    $city = $row[$field_city_col];
    $matches[$city] = $city;
  }

  $matches = array_unique($matches);

  print drupal_to_js($matches);
  exit();
}


/**
 * Фукнция получения массива городов с  указанием страны, к которому принадлежит город
 */
function dm_get_cities_by_country() {
  $cities = array();  
  // @TODO добавить кэширование

  if (defined('DM_MAP_VIEW_NAME')) {
    $results = views_get_view_result(DM_MAP_VIEW_NAME, DM_CITIES_VIEW_DISPLAY_NAME);
    if (!empty($results)) {
      foreach ($results as $i => $row) {
        $country = $row->term_data_tid;
        if (!empty($country)) {
          $city = $row->node_data_field_city_field_city_value;
          $cities[$country][] = $city;
        }
      }
    }
  }
  if (!empty($cities)) {
    foreach ($cities as $country => $array) {
      $cities[$country] = array_unique($array);
      sort($cities[$country]);
    }
  }

  return $cities;
}

function dm_add_js_vars_about_cities() {
  $links = array();
  $cities_by_country = dm_get_cities_by_country();
  if (!empty($cities_by_country)) {
    foreach ($cities_by_country as $country => $cities) {
      for ($i = 0; $i < count($cities); $i++) {
        $link['href'] = sprintf('%s?country=%d&city=%s', DM_BASE_URL, $country, $cities[$i]);
        $link['title'] = $cities[$i];
        $links[] = $link;
      }
    }
  }

  // выводим в js 
  drupal_add_js(array(
    'dfunc_map' => array(
      'cities_links_block' => theme('dm_cities_links', $links),
    ),
  ), 'setting');
}
