<?php
/*
 * Модуль views_ymap
 */

// машинное имя типа материала, который должен отображаться на карте
define('VY_OBJECT_NODE_TYPE_NAME', 'views_ymap_object');
// машинное имя вьюса, который должен содержать карту
define('VY_MAP_VIEW_NAME', 'views_ymap');
// машинное имя дисплея вьюса, который должен содержать карту
define('VY_MAP_DISPLAY_NAME', 'page');

define('VY_CITIES_VIEW_DISPLAY_NAME', 'block_1');

define('VY_BASE_URL', '/views-ymap');

function views_ymap_views_post_render(&$views) {
 // dsm($views); 
}
function views_ymap_views_pre_render(&$view) {
  switch ($view->name) {
    case VY_MAP_VIEW_NAME:
      switch ($view->current_display) {
        case VY_MAP_DISPLAY_NAME:
          vy_add_js_vars_about_objects($view);
          vy_add_scripts();
          break;
      }
      break;
  }
}


/**
 * Создает в js объекты, содержащие данные о найденных объектах,
 * которые надо отобразить на карте
 */
function vy_add_js_vars_about_objects($view) {
  $objects = array();

  $results = $view->result;
  if (!empty($results)) {
    foreach ($results as $i => $row) {
      $balloon = array(
        'title' => $row->node_title,
        'body'  => '',
      );
      $balloon = module_invoke_all('vy_add_js_vars_about_objects', $balloon, $row);

      $object = array(
        'nid' => $row->nid,
        'lat' => $row->field_field_lat[0]['raw']['value'],
        'lon' => $row->field_field_lon[0]['raw']['value'],
        'balloon' => $balloon,
      );
      $objects[] = $object;
    }
  }

  // выводим в js все найденные объекты
  drupal_add_js(array(
    'views_ymap' => array(
      'map_objects' => $objects,
    ),
  ), 'setting');
}

function vy_add_scripts() {
  drupal_add_js('http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU', 'external');

  $module_path = drupal_get_path('module', 'views_ymap');
  drupal_add_js($module_path . '/js/vy_map.js');
  drupal_add_js($module_path . '/js/vy_city_filter.js');

  drupal_add_css($module_path . '/css/vy_map.css');
}

